version: "3"
services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "python3"
    tty: true
    volumes:
      - ./app:/bot
    env_file:
      - .env
  code:
    image: codercom/code-server
    restart: always
    ports:
      - "8443:8443"
    volumes:
      - ./app:/home/coder/project

